// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTdhz60tXL9XXOhwT78M3-Lgb3Z-fUtW8',
    appId: '1:1038743814348:web:7a0649fdcceea3fa08c269',
    messagingSenderId: '1038743814348',
    projectId: 'githubloginexample',
    authDomain: 'githubloginexample.firebaseapp.com',
    storageBucket: 'githubloginexample.appspot.com',
    measurementId: 'G-6F0W3FP3B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZs-c8WESCW6viSUiJiRIeSIvfJfzssGo',
    appId: '1:1038743814348:android:044d34c717e1ae6108c269',
    messagingSenderId: '1038743814348',
    projectId: 'githubloginexample',
    storageBucket: 'githubloginexample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2y0uSsKSioVXBQlcnN4aiOCluMZNCXg',
    appId: '1:1038743814348:ios:08c0dc4a5dbbbb3b08c269',
    messagingSenderId: '1038743814348',
    projectId: 'githubloginexample',
    storageBucket: 'githubloginexample.appspot.com',
    iosBundleId: 'com.example.loginGithubExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2y0uSsKSioVXBQlcnN4aiOCluMZNCXg',
    appId: '1:1038743814348:ios:08c0dc4a5dbbbb3b08c269',
    messagingSenderId: '1038743814348',
    projectId: 'githubloginexample',
    storageBucket: 'githubloginexample.appspot.com',
    iosBundleId: 'com.example.loginGithubExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTdhz60tXL9XXOhwT78M3-Lgb3Z-fUtW8',
    appId: '1:1038743814348:web:1a2c0cf3583c6d4308c269',
    messagingSenderId: '1038743814348',
    projectId: 'githubloginexample',
    authDomain: 'githubloginexample.firebaseapp.com',
    storageBucket: 'githubloginexample.appspot.com',
    measurementId: 'G-2QC615N6CD',
  );
}
